ARCHS = armv7 arm64
DEBUG = 0
PACKAGE_VERSION=1.0

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = VerifiedBadgeForInstagram
VerifiedBadgeForInstagram_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS_MAKE_PATH)/aggregate.mk
